package com.smartfreight.shipment.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Core shipment aggregate root.
 *
 * <p>Persisted to Aurora PostgreSQL (shipment-db) in the {@code shipments} table.
 * Each shipment has one or more {@link ShipmentLeg} records for multi-leg routes.
 */
@Entity
@Table(name = "shipments", indexes = {
        @Index(name = "idx_shipments_reference_no", columnList = "reference_no"),
        @Index(name = "idx_shipments_shipper_id", columnList = "shipper_id"),
        @Index(name = "idx_shipments_status", columnList = "status"),
        @Index(name = "idx_shipments_carrier_id", columnList = "carrier_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Shipment {

    @Id
    @Column(name = "id", updatable = false, nullable = false, length = 36)
    @Builder.Default
    private String id = UUID.randomUUID().toString();

    /**
     * Human-readable reference number (e.g., SF-2024-001234).
     * Generated by the service, shown on shipping labels and in emails.
     */
    @Column(name = "reference_no", unique = true, nullable = false, length = 20)
    private String referenceNumber;

    @Column(name = "shipper_id", nullable = false, length = 36)
    private String shipperId;

    @Column(name = "shipper_name", nullable = false, length = 200)
    private String shipperName;

    @Column(name = "shipper_email", nullable = false, length = 255)
    private String shipperEmail;

    @Column(name = "consignee_id", length = 36)
    private String consigneeId;

    @Column(name = "consignee_name", length = 200)
    private String consigneeName;

    @Column(name = "consignee_email", length = 255)
    private String consigneeEmail;

    // ─── Origin Address ───────────────────────────────────────────────────────

    @Column(name = "origin_street", length = 255)
    private String originStreet;

    @Column(name = "origin_city", nullable = false, length = 100)
    private String originCity;

    @Column(name = "origin_state", nullable = false, length = 50)
    private String originState;

    @Column(name = "origin_zip", length = 20)
    private String originZip;

    @Column(name = "origin_country", nullable = false, length = 2)
    @Builder.Default
    private String originCountry = "US";

    // ─── Destination Address ──────────────────────────────────────────────────

    @Column(name = "dest_street", length = 255)
    private String destinationStreet;

    @Column(name = "dest_city", nullable = false, length = 100)
    private String destinationCity;

    @Column(name = "dest_state", nullable = false, length = 50)
    private String destinationState;

    @Column(name = "dest_zip", length = 20)
    private String destinationZip;

    @Column(name = "dest_country", nullable = false, length = 2)
    @Builder.Default
    private String destinationCountry = "US";

    // ─── Carrier Assignment ───────────────────────────────────────────────────

    @Column(name = "carrier_id", length = 36)
    private String carrierId;

    @Column(name = "carrier_name", length = 200)
    private String carrierName;

    @Column(name = "carrier_tracking_number", length = 100)
    private String carrierTrackingNumber;

    @Column(name = "carrier_rate_id", length = 36)
    private String carrierRateId;

    @Column(name = "negotiated_rate", precision = 10, scale = 2)
    private BigDecimal negotiatedRate;

    // ─── Shipment Details ─────────────────────────────────────────────────────

    @Column(name = "weight_lbs", precision = 10, scale = 2)
    private BigDecimal weightLbs;

    @Column(name = "declared_value", precision = 12, scale = 2)
    private BigDecimal declaredValue;

    @Column(name = "currency", length = 3)
    @Builder.Default
    private String currency = "USD";

    @Column(name = "special_instructions", columnDefinition = "TEXT")
    private String specialInstructions;

    // ─── Status and Timeline ──────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    @Builder.Default
    private ShipmentStatus status = ShipmentStatus.CREATED;

    @Column(name = "estimated_delivery")
    private Instant estimatedDelivery;

    @Column(name = "actual_delivery")
    private Instant actualDelivery;

    @Column(name = "pod_document_key", length = 500)
    private String podDocumentKey;

    @Column(name = "recipient_name", length = 200)
    private String recipientName;

    @Column(name = "gl_code", length = 20)
    private String glCode;

    // ─── Audit Fields ─────────────────────────────────────────────────────────

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    @Column(name = "created_by", updatable = false, length = 36)
    private String createdBy;

    /** Optimistic locking — prevents concurrent status updates corrupting state. */
    @Version
    @Column(name = "version")
    private Long version;

    // ─── Relationships ────────────────────────────────────────────────────────

    @OneToMany(mappedBy = "shipment", cascade = CascadeType.ALL, orphanRemoval = true,
               fetch = FetchType.LAZY)
    @OrderBy("sequence ASC")
    @Builder.Default
    private List<ShipmentLeg> legs = new ArrayList<>();

    // ─── Business Methods ─────────────────────────────────────────────────────

    /**
     * Transitions the shipment to the given status after validating the transition.
     * This is the ONLY way to change the status — direct setter is intentionally avoided
     * to enforce the state machine.
     *
     * @throws com.smartfreight.common.exceptions.BusinessRuleViolationException if invalid
     */
    public void transitionTo(ShipmentStatus newStatus) {
        this.status.validateTransitionTo(this.id, newStatus);
        this.status = newStatus;
    }

    /** Returns the city/state display string for the origin. */
    public String originDisplayName() {
        return originCity + ", " + originState;
    }

    /** Returns the city/state display string for the destination. */
    public String destinationDisplayName() {
        return destinationCity + ", " + destinationState;
    }
}
